name: gr_zoom
description: A Flutter plugin for the Zoom Client SDK.
version: 1.1.0+2
repository: https://github.com/25LucasAnselmo/gr_zoom
homepage: https://github.com/25LucasAnselmo

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.6.4
  lint: ^2.3.0
 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.webcare.zoom
        pluginClass: ZoomPlugin
      ios:
        pluginClass: ZoomPlugin